program ParcelasTestes;

uses
  vcl.Forms,
  TestFramework,
  GUITestRunner,
  IWInit,
  IWGlobal,
  untTestCasePedido in 'units\untTestCasePedido.pas',
  untTFaker in 'units\untTFaker.pas',
  untTestCaseDAOs in 'units\untTestCaseDAOs.pas',
  untTPedidoFactory in 'units\untTPedidoFactory.pas',
  Dominio.Entidades.TCliente in '..\units\Dominio\Entidades\Dominio.Entidades.TCliente.pas',
  Dominio.Entidades.TEmitente in '..\units\Dominio\Entidades\Dominio.Entidades.TEmitente.pas',
  Dominio.Entidades.TFactory in '..\units\Dominio\Entidades\Dominio.Entidades.TFactory.pas',
  Dominio.Entidades.TFormaPagto in '..\units\Dominio\Entidades\Dominio.Entidades.TFormaPagto.pas',
  Dominio.Entidades.TFornecedor in '..\units\Dominio\Entidades\Dominio.Entidades.TFornecedor.pas',
  Dominio.Entidades.TItemPedido in '..\units\Dominio\Entidades\Dominio.Entidades.TItemPedido.pas',
  Dominio.Entidades.TParcelas in '..\units\Dominio\Entidades\Dominio.Entidades.TParcelas.pas',
  Dominio.Entidades.TPedido in '..\units\Dominio\Entidades\Dominio.Entidades.TPedido.pas',
  Dominio.Entidades.TProduto in '..\units\Dominio\Entidades\Dominio.Entidades.TProduto.pas',
  Dominio.Entidades.TVendedor in '..\units\Dominio\Entidades\Dominio.Entidades.TVendedor.pas',
  Dao.IDAOCliente in '..\units\Dao\Abstract\Dao.IDAOCliente.pas',
  Dao.IDaoEmitente in '..\units\Dao\Abstract\Dao.IDaoEmitente.pas',
  Dao.IDaoFormaPagto in '..\units\Dao\Abstract\Dao.IDaoFormaPagto.pas',
  Dao.IDaoFornecedor in '..\units\Dao\Abstract\Dao.IDaoFornecedor.pas',
  Dao.IDaoItemPedido in '..\units\Dao\Abstract\Dao.IDaoItemPedido.pas',
  Dao.IDaoParametros in '..\units\Dao\Abstract\Dao.IDaoParametros.pas',
  Dao.IDaoParcelas in '..\units\Dao\Abstract\Dao.IDaoParcelas.pas',
  Dao.IDaoPedido in '..\units\Dao\Abstract\Dao.IDaoPedido.pas',
  Dao.IDaoProdutos in '..\units\Dao\Abstract\Dao.IDaoProdutos.pas',
  Dao.IDaoVendedor in '..\units\Dao\Abstract\Dao.IDaoVendedor.pas',
  Dao.TDaoCliente in '..\units\Dao\Concret\Dao.TDaoCliente.pas',
  Dao.TDaoEmitente in '..\units\Dao\Concret\Dao.TDaoEmitente.pas',
  Dao.TDaoFormaPagto in '..\units\Dao\Concret\Dao.TDaoFormaPagto.pas',
  Dao.TDaoFornecedor in '..\units\Dao\Concret\Dao.TDaoFornecedor.pas',
  Dao.TDaoItemPedido in '..\units\Dao\Concret\Dao.TDaoItemPedido.pas',
  Dao.TDaoParametros in '..\units\Dao\Concret\Dao.TDaoParametros.pas',
  Dao.TDaoParcelas in '..\units\Dao\Concret\Dao.TDaoParcelas.pas',
  Dao.TDaoPedido in '..\units\Dao\Concret\Dao.TDaoPedido.pas',
  Dao.TDaoProdutos in '..\units\Dao\Concret\Dao.TDaoProdutos.pas',
  Dao.TDaoVendedor in '..\units\Dao\Concret\Dao.TDaoVendedor.pas',
  Sistema.TParametros in '..\units\Sistema\Sistema.TParametros.pas',
  Impressao.TParametrosImpressora in '..\units\Impressao\Impressao.TParametrosImpressora.pas',
  untTestCaseDatabaseMigration in 'units\untTestCaseDatabaseMigration.pas',
  Database.TTabelaBDFB in '..\units\Database\Concret\Database.TTabelaBDFB.pas',
  Database.IDataseMigration in '..\units\Database\Abstract\Database.IDataseMigration.pas',
  Dominio.Mapeamento.Atributos in '..\units\Dominio\Mapeamento\Dominio.Mapeamento.Atributos.pas',
  Database.TDataseMigrationBase in '..\units\Database\Concret\Database.TDataseMigrationBase.pas',
  Database.TTabelaBD in '..\units\Database\Abstract\Database.TTabelaBD.pas',
  Dominio.Mapeamento.Tipos in '..\units\Dominio\Mapeamento\Dominio.Mapeamento.Tipos.pas',
  Dao.IDAOPedidoPeriodo in '..\units\Dao\Abstract\Dao.IDAOPedidoPeriodo.pas',
  Helper.TPedidoPeriodo in '..\units\helper\Helper.TPedidoPeriodo.pas',
  Dao.TDaoPedidoPeriodo in '..\units\Dao\Concret\Dao.TDaoPedidoPeriodo.pas',
  untTestCaseLicenca in 'units\untTestCaseLicenca.pas',
  Sistema.TLicenca in '..\units\Sistema\Sistema.TLicenca.pas',
  DCPbase64 in '..\units\Cript\DCPbase64.pas',
  DCPconst in '..\units\Cript\DCPconst.pas',
  DCPcrypt2 in '..\units\Cript\DCPcrypt2.pas',
  DCPripemd160 in '..\units\Cript\DCPripemd160.pas',
  DCPsha1 in '..\units\Cript\DCPsha1.pas',
  DCPrc4 in '..\units\Cript\DCPrc4.pas',
  Util.VclFuncoes in '..\units\Util\Util.VclFuncoes.pas',
  Dominio.Entidades.TEntity in '..\..\Repositorio\Dominio\Dominio.Entidades.TEntity.pas',
  Dao.TDaoBase in '..\..\Repositorio\DAO\Dao.TDaoBase.pas',
  Util.Exceptions in '..\..\Repositorio\Util\Util.Exceptions.pas',
  Util.Funcoes in '..\..\Repositorio\Util\Util.Funcoes.pas',
  Util.TSerial in '..\..\Repositorio\Util\Util.TSerial.pas',
  untTestCaseOrcamento in 'units\untTestCaseOrcamento.pas',
  Dominio.Entidades.TItemOrcamento in '..\units\Dominio\Entidades\Dominio.Entidades.TItemOrcamento.pas',
  Dominio.Entidades.TOrcamento in '..\units\Dominio\Entidades\Dominio.Entidades.TOrcamento.pas',
  Dao.TDaoItemOrcamento in '..\units\Dao\Concret\Dao.TDaoItemOrcamento.pas',
  Dao.TDaoOrcamento in '..\units\Dao\Concret\Dao.TDaoOrcamento.pas',
  untTOrcamentoFactory in 'units\untTOrcamentoFactory.pas',
  Dao.IDaoOrcamento in '..\units\Dao\Abstract\Dao.IDaoOrcamento.pas';

{$R *.res}

begin
   //GAppModeInit(Application);
  TGUITestRunner.runRegisteredTests;
end.
